import Head from "next/head";
import { GetServerSideProps } from "next";
import Image from "next/image";
import Header from "../components/Header";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* Nav */}
      <NavBar />
      {/* Results */}
    </div>
  );
}

// export async function GetServerSideProps(context) {
//   const req = fetch(`https://api.themoviedb.org/3/`);
// }
